server:
  port: 8091

spring:
  datasource:
    db1:
#      type: com.zaxxer.hikari.HikariDataSource
#      maximum-pool-size: 50
#      minimum-idle: 5
#      pool-name: db1-pool
#      connection-test-query: SELECT 1 FROM DUAL
      url: jdbc:postgresql://localhost:5433/first_db
      username: blessed
      password: password123
      driver-class-name: org.postgresql.Driver

    db2:
#      type: com.zaxxer.hikari.HikariDataSource
#      maximum-pool-size: 2
#      minimum-idle: 1
#      pool-name: db1-pool
#      connection-test-query: SELECT 1 FROM DUAL
      url: jdbc:postgresql://localhost:5435/second_db
      username: blessed
      password: password123
      driver-class-name: org.postgresql.Driver












#server.port=8091
## First DataSource
#spring.datasource.first.jdbc-url=jdbc:postgresql://localhost:5433/first_db
#spring.datasource.first.username=blessed
#spring.datasource.first.password=password123
#spring.datasource.first.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.default_schema: public
## Second DataSource
#db2.datasource.second.jdbc-url=jdbc:postgresql://localhost:5435/second_db
#db2.datasource.second.username=blessed
#db2.datasource.second.password=password123
#db2.datasource.second.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#
#spring.datasource.first.hikari.connectionTimeout=30
#spring.datasource.first.hikari.idleTimeout=60
#spring.datasource.first.hikari.maxLifetime=1000
#spring.datasource.first.hikari.auto-commit=false
#spring.datasource.first.hikari.maximum-pool-size=5
#
#
#spring.datasource.second.hikari.connectionTimeout= 30000
#spring.datasource.second.hikari.idleTimeout= 600000
#spring.datasource.second.hikari.maxLifetime= 1800000
